const menulogos = (sender, prefix) => {
return `༒W̷E̷L̷C̷O̷M̷E̷༒
⇒ @${sender.split("@")[0]}

『 𝐓𝐄𝐗𝐓𝐎 𝐈𝐈 』
╭════════════════════╯
 | ೈ፝͜͡📜 ${prefix}marvel (txt/txt)
 | ೈ፝͜͡📜 ${prefix}pornhub (txt/txt)
 | ೈ፝͜͡📜 ${prefix}space (txt/txt)
 | ೈ፝͜͡📜 ${prefix}stone (txt/txt)
 | ೈ፝͜͡📜 ${prefix}steel (txt/txt)
 | ೈ፝͜͡📜 ${prefix}grafity (txt/txt)
 | ೈ፝͜͡📜 ${prefix}glitch3 (txt/txt)
 | ೈ፝͜͡📜 ${prefix}america (txt/txt)
 ╰════════════════════╮
 『 𝐓𝐄𝐗𝐓𝐎 𝐈 』
 ╭════════════════════╯
 | ೈ፝͜͡📜 ${prefix}shadow (txt)
 | ೈ፝͜͡📜 ${prefix}metalgold (txt)
 | ೈ፝͜͡📜 ${prefix}cup (txt)
 | ೈ፝͜͡📜 ${prefix}txtborboleta (txt)
 | ೈ፝͜͡📜 ${prefix}cemiterio (txt)
 | ೈ፝͜͡📜 ${prefix}efeitoneon (txt)
 | ೈ፝͜͡📜 ${prefix}harryp (txt)
 | ೈ፝͜͡📜 ${prefix}lobometal (txt)
 | ೈ፝͜͡📜 ${prefix}neon2 (txt)
 | ೈ፝͜͡📜 ${prefix}madeira (txt)
 | ೈ፝͜͡📜 ${prefix}coffecup (txt)
 | ೈ፝͜͡📜 ${prefix}coffecup2 (txt)
 | ೈ፝͜͡📜 ${prefix}florwooden (txt)
 | ೈ፝͜͡📜 ${prefix}narutologo (txt)
 | ೈ፝͜͡📜 ${prefix}fire (txt)
 | ೈ፝͜͡📜 ${prefix}romantic (txt)
 | ೈ፝͜͡📜 ${prefix}smoke (txt)
 | ೈ፝͜͡📜 ${prefix}papel (txt)
 | ೈ፝͜͡📜 ${prefix}lovemsg (txt)
 | ೈ፝͜͡📜 ${prefix}lovemsg2 (txt)
 | ೈ፝͜͡📜 ${prefix}lovemsg3 (txt)
 | ೈ፝͜͡📜 ${prefix}fiction (txt)
 | ೈ፝͜͡📜 ${prefix}3dstone (txt)
 | ೈ፝͜͡📜 ${prefix}areia (txt)
 | ೈ፝͜͡📜 ${prefix}style (txt)
 | ೈ፝͜͡📜 ${prefix}blood (txt)
 | ೈ፝͜͡📜 ${prefix}pink (txt)
 | ೈ፝͜͡📜 ${prefix}cattxt (txt)
 | ೈ፝͜͡📜 ${prefix}neondevil (txt)
 | ೈ፝͜͡📜 ${prefix}carbon (txt)
 | ೈ፝͜͡📜 ${prefix}metalfire (txt)
 | ೈ፝͜͡📜 ${prefix}thunder (txt)
 | ೈ፝͜͡📜 ${prefix}vidro (txt)
 | ೈ፝͜͡📜 ${prefix}jokerlogo (txt)
 | ೈ፝͜͡📜 ${prefix}transformer (txt)
 | ೈ፝͜͡📜 ${prefix}demonfire (txt)
 | ೈ፝͜͡📜 ${prefix}jeans (txt)
 | ೈ፝͜͡📜 ${prefix}metalblue (txt)
 | ೈ፝͜͡📜 ${prefix}natal (txt)
 | ೈ፝͜͡📜 ${prefix}ossos (txt)
 | ೈ፝͜͡📜 ${prefix}asfalto (txt)
 | ೈ፝͜͡📜 ${prefix}break (txt)
 | ೈ፝͜͡📜 ${prefix}glitch2 (txt)
 | ೈ፝͜͡📜 ${prefix}colaq (txt)
 | ೈ፝͜͡📜 ${prefix}neon3 (txt)
 | ೈ፝͜͡📜 ${prefix}nuvem (txt)
 | ೈ፝͜͡📜 ${prefix}horror (txt)
 | ೈ፝͜͡📜 ${prefix}matrix (txt)
 | ೈ፝͜͡📜 ${prefix}berry (txt)
 | ೈ፝͜͡📜 ${prefix}luxury (txt)
 | ೈ፝͜͡📜 ${prefix}lava (txt)
 | ೈ፝͜͡📜 ${prefix}thunderv2 (txt)
 | ೈ፝͜͡📜 ${prefix}neongreen (txt)
 | ೈ፝͜͡📜 ${prefix}neve (txt)
 | ೈ፝͜͡📜 ${prefix}neon (txt)
 | ೈ፝͜͡📜 ${prefix}neon1 (txt)
 | ೈ፝͜͡📜 ${prefix}neon3d (txt)
 | ೈ፝͜͡📜 ${prefix}gelo (txt)
 | ೈ፝͜͡📜 ${prefix}neon3 (txt)
 | ೈ፝͜͡📜 ${prefix}3dgold (txt)
 | ೈ፝͜͡📜 ${prefix}lapis (txt)
 | ೈ፝͜͡📜 ${prefix}toxic (txt)
 | ೈ፝͜͡📜 ${prefix}demongreen (txt)
 | ೈ፝͜͡📜 ${prefix}rainbow (txt)
 | ೈ፝͜͡📜 ${prefix}halloween (txt)
 | ೈ፝͜͡📜 ${prefix}angelwing (txt)
 | ೈ፝͜͡📜 ${prefix}hackneon (txt)
 | ೈ፝͜͡📜 ${prefix}fpsmascote (txt)
 | ೈ፝͜͡📜 ${prefix}equipemascote (txt)
 | ೈ፝͜͡📜 ${prefix}txtquadrinhos (txt)
 | ೈ፝͜͡📜 ${prefix}ffavatar (txt)
 | ೈ፝͜͡📜 ${prefix}mascotegame (txt)
 | ೈ፝͜͡📜 ${prefix}angelglx (txt)
 | ೈ፝͜͡📜 ${prefix}gizquadro (txt)
 | ೈ፝͜͡📜 ${prefix}wingeffect (txt)
 | ೈ፝͜͡📜 ${prefix}blackpink (txt)
 | ೈ፝͜͡📜 ${prefix}metalgold (txt)
 | ೈ፝͜͡📜 ${prefix}girlmascote (txt)
 | ೈ፝͜͡📜 ${prefix}logogame (txt)
╰════════════════════╮`
}

exports.menulogos = menulogos